apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mitul01/robot-shop-config.git
    targetRevision: HEAD
    path: robot-shop
  destination:
    server: https://kubernetes.default.svc
    namespace: robot-shop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true